### ISSUE TITLE
I want mail123456.com

### ISSUE THREAD

**Issue by Raytle** [j256/mailgw#10]
>> http://www.mailgw.com/ is difficult for me to remember. On the other hand, http://www.mail123456.com/ is easy for me to remember.

> Sorry about that.

No problem. I've worked with many engineers. They have all been terrible at UI/UX (user interface/user experience).

> >When I used Spamgourmet.com I rarely used that email. I used one of their other domains "recursor.net" so that I might create an email address such as...

> There are other domains that map to mailgw.com.  spam86.com is one of them.  mnull.com is another.  

I see.

> Is that what you want

No.

I want **mail123456.com**.

Bad design makes people learn new stuff unnecessarily. Because I presume all users of Mailgw.com know how to count from one to ten, then something like **mail123456** would almost certainly be easier for them to remember than domains **spam86.com** and **mnull.com**.

I am thinking of the following use case...

1. I am signing up for a new website.
2. I need to enter an email address.
3. I am creating a new  email address "on the fly" (to avoid being spammed in the future).
4. I can more remember to type in "mail123456.com" at the end of, for example, **Free_Chocolate_Chip_Cookie.3.yek@mail123456.com** (to receive a free chocolate chip cookie in the mail) more easily than **yek.freechocolatechipcookie@spam86.com**

And yeah, of course, that's a feature request. Mailgw **obviously** should allow users to include capital letters, underscores, and dashes in email addresses. Please don't take offense but disallowing them is obviously bad practice. If your code "breaks" because of that, well, then, ummm, hmmmm... I suggest you update your code. It's not 1996 any longer!

**Comment by j256** [comment]
Wow.  Can you be more condescending?

> No problem. I've worked with many engineers. They have all been terrible at UI/UX (user interface/user experience).

I've worked with a lot of UI/UX engineers who didn't appreciate how complex some of the inner workings of the technology they are decorating.

> I want mail123456.com.

How about you pay me $200/month and I'll stand up your own instance of mailgw on that domain?

> Bad design makes people learn new stuff unnecessarily.

So you want me to change the domain name.  For you.  Because that will be a better "design" and will cause "people" to not have to learn new stuff?  Just making sure I understand you.

> Mailgw obviously should allow users to include capital letters, underscores, and dashes in email addresses.

Obviously. First off, according to the RFC, email addresses are case sensitive.  So no.  Underscores and dashes could be allowed but I'm not going to do it.  I've used dashes to recognize the response addresses easily and I don't want them to clash.

> Please don't take offense but disallowing them is obviously bad practice

Obvious to you maybe.  Not to me.  Gmail doesn't allow underscores (for example) so it also wasn't "obvious" the Google engineers.  But I'm sure you know more than them too.

> It's not 1996 any longer!

So true.  Well said.
